---
- name: Setup Docker and Deploy Nginx
  hosts: yeah
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Create HTML directory
      file:
        path: /opt/html
        state: directory

    - name: Copy index.html to container path
      copy:
        src: files/index.html
        dest: /opt/html/index.html

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - /opt/html:/usr/share/nginx/html:ro
